import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header/Index";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { AuthProvider } from "../context/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
  params: { locale }
}) {
  const selectedLocale = locale || 'en';

  let messages;
  try {
    messages = await getMessages(selectedLocale);
  } catch (error) {
    console.error(`Error fetching messages for locale ${selectedLocale}:`, error);
    messages = await getMessages('en'); 
  }

  return (
    <html lang={selectedLocale} dir={selectedLocale === 'ar' ? 'rtl' : 'ltr'}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa+Ink:wght@400;700&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap" rel="stylesheet" />
        
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <AuthProvider> 
          <NextIntlClientProvider messages={messages}>
            <div className="shadow-lg">
              <Header />
            </div>
            <main>{children}</main>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
